name: frontend-build

on:
    push:
        branches: ["*"]
    pull_request:
        branches: [trunk]
    workflow_dispatch:

jobs:
    build:
        env:
            DOTNET_NOLOGO: true
            DOTNET_CLI_TELEMETRY_OPTOUT: true
            ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false
            # Set the locale
            LC_ALL: en_US.UTF-8
            LANG: en_US.UTF-8
        runs-on: ubuntu-latest
        if: always()

        steps:
            - uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: npm install
              # Using Cypress action for caching optimization (saves ~3mins of downloading Cypress every build)
              uses: cypress-io/github-action@v2
              with:
                  # Skipping actual tests for now - requires dotnet & webpack running
                  runTests: false
                  working-directory: frontend

            - name: npm run test
              run: |
                  cd frontend
                  npm run test -- --coverage

            - name: npm run build
              run: |
                  cd frontend
                  npm run build

            - name: Upload to codecov
              uses: codecov/codecov-action@v1
