name: backend-deploy

on:
    push:
        branches: ["*"]
    pull_request:
        branches: [trunk]
    workflow_dispatch:

jobs:
    build:
        env:
            DOTNET_NOLOGO: true
            DOTNET_CLI_TELEMETRY_OPTOUT: true
            ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false
            # Set the locale
            LC_ALL: en_US.UTF-8
            LANG: en_US.UTF-8
        runs-on: ubuntu-latest
        if: always()

        steps:
            - uses: actions/checkout@v2

            - name: Setup Docker
              uses: docker-practice/actions-setup-docker@master

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: "5.0.405"

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Output dotnet info
              run: dotnet --info

            - name: Dotnet tests
              run: |
                  dotnet restore dotnet/api/Api.sln
                  dotnet test dotnet/api/Api.sln -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:Threshold=0 --filter "Category!=SkipCI"

            - name: npm install
              # Using Cypress action for caching optimization (saves ~3mins of downloading Cypress every build)
              uses: cypress-io/github-action@v2
              with:
                  # Skipping actual tests for now - requires dotnet & webpack running
                  runTests: false
                  working-directory: frontend

            - name: npm run test
              run: |
                  cd frontend
                  npm run test -- --coverage

            - name: Upload to codecov
              uses: codecov/codecov-action@v1
