name: backend-deploy

on:
    push:
        branches: ["*"]
    pull_request:
        branches: [trunk]
    workflow_dispatch:

jobs:
    build:
        env:
            AZURE_WEBAPP_NAME: app-gravityboots-backend-dev    # set this to your application's name
            AZURE_WEBAPP_PACKAGE_PATH: 'dotnet/api'      # set this to the path to your web app project, defaults to the repository root
            DOTNET_NOLOGO: true
            DOTNET_CLI_TELEMETRY_OPTOUT: true
            ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false
            # Set the locale
            LC_ALL: en_US.UTF-8
            LANG: en_US.UTF-8
        runs-on: ubuntu-latest
        if: always()

        steps:
            - uses: actions/checkout@v2

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: "5.0.405"

            - name: dotnet build and publish
              run: |
                dotnet restore
                dotnet build --project dotnet/api/ --configuration Release
                dotnet publish --project dotnet/api -c Release

            - name: 'Login via Azure CLI'
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

            # Deploy to Azure Web apps
            - name: 'Run Azure webapp deploy action using publish profile credentials'
              uses: azure/webapps-deploy@v2
              with:
                app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
                package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/release'
